<html>
	<head>
		<meta charset="utf-8" />
		<title>Petgram | <?= $this->view->titlePage ?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="./img/favicon.ico" type="image/x-icon">

		<!-- Estilo próprio -->
		<link rel="stylesheet" href="./css/main.css">
	</head>

	<body>
		<main id="error">
			<section class="info">
				<h1>Oops...</h1>
				<p>A página que você procura não existe ou o usuário foi desativado.</p>
				<a href="/search">Pesquisar novamente</a>
			</section>
        </main>
		<footer class="createdBy auth">criado por <br><a target="_blank" href="https://github.com/brunoibarbosa/">BRUNO INACIO</a></footer>
	</body>

</html>