<html>
	<head>
		<meta charset="utf-8" />
		<title>Petgram | <?= $this->view->titlePage ?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="./img/favicon.ico" type="image/x-icon">

		<!-- Estilo próprio -->
		<link rel="stylesheet" href="./css/main.css">
		<link rel="stylesheet" href="./css/auth.css">

		<!-- UIcons -->
		<link rel="stylesheet" href="./css/uicons-regular-rounded.css">
		<link rel="stylesheet" href="./css/uicons-solid-rounded.css">
	</head>

	<body>
		<?= $this->content() ?>
		<footer class="createdBy auth">criado por <br><a target="_blank" href="https://github.com/brunoibarbosa/">BRUNO INACIO</a></footer>

		<script src="./js/main.js"></script>
	</body>

</html>

<?php
	if (isset($_SESSION['errors'])) unset($_SESSION['errors']);
	if (isset($_SESSION['errors'])) unset($_SESSION['userForm']);
?>