<section class="form-home">
	<img src="./img/petgram-logo.svg" alt="Petgram" width="175">
	<form action="/account-login" id="form-login" method="get">
		<section>
			<label class="entry">
				<input type="text" value="<?= $this->view->userForm['entry'] ?>" name="entry" required>
				<span>Nome de usuário ou email</span>
			</label>
		</section>
		<section>
			<label class="password">
				<input type="password" name="password" required id="passwordInput">
				<span>Senha</span>
				<button class="showPass" type="button"><i class="fi-rr-eye-crossed"></i></button>
			</label>
		</section>
		<section><button type="submit" disabled>Entrar</button></section>
	</form>
	<?php if(isset($_SESSION['errors']) && count($_SESSION['errors']) > 0) { ?>
		<section class="errors-form">
		<?php foreach ($_SESSION['errors'] as $key => $error) { ?>
			<p><?= $error ?></p>
		<?php }?>
		</section>
	<?php } ?>
	<section><span class="span-register">Não tem uma conta? <a href="/register">Cadastre-se</a></span></section>
</section>