<main id="comments">
    <section class="comments">
        <ul>
            <a class="backToPhoto" href="/photo?p=<?= $_GET['p'] ?>"><i class="fi-rr-arrow-left"></i> Voltar para a foto</a>
            <?php foreach ($this->view->photo->comments as $key => $comment) { ?>
                <li class="comment">
                    <section class="user-picture">
                        <a href="/profile?user=<?= $comment->user->username ?>"><img src="<?= $comment->user->picture ?>" alt="Foto de Perfil"></a>
                    </section>
                    <section class="content">
                        <section>
                            <a href="/profile?user=<?= $comment->user->username ?>"><?= $comment->user->username ?></a>
                            <span>• <?= $comment->register_date ?></span>
                        </section>
                        <p><?= $comment->comment ?></p>
                    </section>
                    <?php if ($_SESSION['user']['id'] == $comment->user->id_petuser) { ?>
                        <a class="btnDeleteComment" href="/delete-comment?comment=<?= $comment->id_comment ?>"><i class="fi-rr-trash"></i></a>
                    <?php } ?>
                </li>
            <?php } ?>
        </ul>
        <?php if ($this->view->totalPages > 1) { ?>
            <section class="buttons-pages">
                <!-- Botão voltar uma página -->
                <?php if ($this->view->currentPage - 1 > 0) { ?>
                    <a class="btnPrevious" href="/comments?p=<?= $_GET['p'] ?>&page=<?= $this->view->currentPage - 1 ?>"><i class="fi-rr-arrow-left"></i></a>
                <?php } ?>

                <!-- Botão primeira página -->
                <a class="<?php if ($this->view->currentPage == 1) echo 'active' ?>" href="/comments?p=<?= $_GET['p'] ?>">1</a>

                <!-- ... -->
                <?php if ($this->view->currentPage > 1 && $this->view->currentPage - 2 > 1) { ?>
                    <span>...</span>
                <?php } ?>

                <!-- Página anterior a ativa -->
                <?php if ($this->view->currentPage > 1 && $this->view->currentPage - 1 > 1) { ?>
                    <a href="/comments?p=<?= $_GET['p'] ?>&page=<?= $this->view->currentPage - 1 ?>"><?= $this->view->currentPage - 1 ?></a>
                <?php } ?>
                
                <!-- Página atual != da primeira e última página -->
                <?php if ($this->view->currentPage > 1 && $this->view->currentPage < $this->view->totalPages) { ?>
                    <a class="active" href="/comments?p=<?= $_GET['p'] ?>&page=<?= $this->view->currentPage ?>"><?= $this->view->currentPage ?></a>
                <?php } ?>

                <!-- Página próxima a ativa -->
                <?php if ($this->view->currentPage < $this->view->totalPages && $this->view->currentPage + 1 < $this->view->totalPages) { ?>
                    <a href="/comments?p=<?= $_GET['p'] ?>&page=<?= $this->view->currentPage + 1 ?>"><?= $this->view->currentPage + 1 ?></a>
                <?php } ?>

                <!-- ... -->
                <?php if ($this->view->currentPage < $this->view->totalPages && $this->view->currentPage + 2 < $this->view->totalPages) { ?>
                    <span>...</span>
                <?php } ?>

                <!-- Botão última página -->
                <?php if ($this->view->totalPages >= 3) { ?>
                    <a class="<?php if ($this->view->currentPage == $this->view->totalPages) echo 'active' ?>" href="/comments?p=<?= $_GET['p'] ?>&page=<?= $this->view->totalPages ?>"><?= $this->view->totalPages ?></a>
                <?php } ?>

                <!-- Botão caso só tenha 2 páginas -->
                <?php if ($this->view->totalPages == 2) { ?>
                    <a class="<?php if ($this->view->currentPage == 2) echo 'active' ?>" href="/comments?p=<?= $_GET['p'] ?>&page=2">2</a>
                <?php } ?>

                <!-- Botão avançar uma página -->
                <?php if ($this->view->currentPage + 1 <= $this->view->totalPages) { ?>
                    <a class="btnNext" href="/comments?p=<?= $_GET['p'] ?>&page=<?= $this->view->currentPage + 1 ?>"><i class="fi-rr-arrow-right"></i></a>
                <?php } ?>
            </section>
            <?php } ?>
    </section>
</main>