<main id="likes">
    <section class="likes">
        <ul>
            <a class="backToPhoto" href="/photo?p=<?= $_GET['p'] ?>"><i class="fi-rr-arrow-left"></i> Voltar para a foto</a>
            <?php if($this->view->likes) { foreach ($this->view->likes as $key => $value) { ?>
            <li class="card">
                <section class="info">
                    <section class="picture">
                        <a href="/profile?user=<?= $value->user->username ?>"><img src="<?= $value->user->picture ?>" alt="Foto de perfil"></a>
                    </section>
                    <section class="user">
                        <a href="/profile?user=<?= $value->user->username ?>"><?= $value->user->username ?></a>
                        <span><?= $value->user->petname ?></span>
                    </section>
                </section>
                <section class="action">
                    <?php if (isset($_SESSION['user']['username']) && $value->user->username != $_SESSION['user']['username']) { if (!$value->followed_by_user) { ?>
                        <a href="/follow?user=<?= $value->user->username ?>" class="follow-btn">Seguir</a>
                    <?php } else { ?>
                        <button type="button" class="unfollow-btn" data-user="<?= $value->user->username ?>">Deixar de seguir</button>
                        <?php }} ?>
                </section>
            </li>
            <?php }} ?>
        </ul>
        <?php if ($this->view->totalPages > 1) { ?>
            <section class="buttons-pages">
                <!-- Botão voltar uma página -->
                <?php if ($this->view->currentPage - 1 > 0) { ?>
                    <a class="btnPrevious" href="/likes?p=<?= $_GET['p'] ?>&page=<?= $this->view->currentPage - 1 ?>"><i class="fi-rr-arrow-left"></i></a>
                <?php } ?>

                <!-- Botão primeira página -->
                <a class="<?php if ($this->view->currentPage == 1) echo 'active' ?>" href="/likes?p=<?= $_GET['p'] ?>">1</a>

                <!-- ... -->
                <?php if ($this->view->currentPage > 1 && $this->view->currentPage - 2 > 1) { ?>
                    <span>...</span>
                <?php } ?>

                <!-- Página anterior a ativa -->
                <?php if ($this->view->currentPage > 1 && $this->view->currentPage - 1 > 1) { ?>
                    <a href="/likes?p=<?= $_GET['p'] ?>&page=<?= $this->view->currentPage - 1 ?>"><?= $this->view->currentPage - 1 ?></a>
                <?php } ?>
                
                <!-- Página atual != da primeira e última página -->
                <?php if ($this->view->currentPage > 1 && $this->view->currentPage < $this->view->totalPages) { ?>
                    <a class="active" href="/likes?p=<?= $_GET['p'] ?>&page=<?= $this->view->currentPage ?>"><?= $this->view->currentPage ?></a>
                <?php } ?>

                <!-- Página próxima a ativa -->
                <?php if ($this->view->currentPage < $this->view->totalPages && $this->view->currentPage + 1 < $this->view->totalPages) { ?>
                    <a href="/likes?p=<?= $_GET['p'] ?>&page=<?= $this->view->currentPage + 1 ?>"><?= $this->view->currentPage + 1 ?></a>
                <?php } ?>

                <!-- ... -->
                <?php if ($this->view->currentPage < $this->view->totalPages && $this->view->currentPage + 2 < $this->view->totalPages) { ?>
                    <span>...</span>
                <?php } ?>

                <!-- Botão última página -->
                <?php if ($this->view->totalPages >= 3) { ?>
                    <a class="<?php if ($this->view->currentPage == $this->view->totalPages) echo 'active' ?>" href="/likes?p=<?= $_GET['p'] ?>&page=<?= $this->view->totalPages ?>"><?= $this->view->totalPages ?></a>
                <?php } ?>

                <!-- Botão caso só tenha 2 páginas -->
                <?php if ($this->view->totalPages == 2) { ?>
                    <a class="<?php if ($this->view->currentPage == 2) echo 'active' ?>" href="/likes?p=<?= $_GET['p'] ?>&page=2">2</a>
                <?php } ?>

                <!-- Botão avançar uma página -->
                <?php if ($this->view->currentPage + 1 <= $this->view->totalPages) { ?>
                    <a class="btnNext" href="/likes?p=<?= $_GET['p'] ?>&page=<?= $this->view->currentPage + 1 ?>"><i class="fi-rr-arrow-right"></i></a>
                <?php } ?>
            </section>
        <?php } ?>
    </section>
</main>